// <auto-generated />
using System;
using DayanismaPortali.Service.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DayanismaPortali.Service.Migrations
{
    [DbContext(typeof(DayanismaPortaliDB))]
    [Migration("20241210155413_mig-2")]
    partial class mig2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DayanismaPortali.Service.Model.Kullanicilar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ilId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ilId");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("DayanismaPortali.Service.Model.Randevular", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Kullanici_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Vakif_ID")
                        .HasColumnType("int");

                    b.Property<bool>("Yapildi_mi")
                        .HasColumnType("bit");

                    b.Property<int>("kullaniciID")
                        .HasColumnType("int");

                    b.Property<int>("vakifID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("kullaniciID");

                    b.HasIndex("vakifID");

                    b.ToTable("Randevu");
                });

            modelBuilder.Entity("DayanismaPortali.Service.Model.Vakiflar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ilID")
                        .HasColumnType("int");

                    b.Property<int?>("il_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ilID");

                    b.ToTable("Vakif");
                });

            modelBuilder.Entity("DayanismaPortali.Service.Model.iller", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("il");
                });

            modelBuilder.Entity("DayanismaPortali.Service.Model.Kullanicilar", b =>
                {
                    b.HasOne("DayanismaPortali.Service.Model.iller", "il")
                        .WithMany("Kullanici")
                        .HasForeignKey("ilId");

                    b.Navigation("il");
                });

            modelBuilder.Entity("DayanismaPortali.Service.Model.Randevular", b =>
                {
                    b.HasOne("DayanismaPortali.Service.Model.Kullanicilar", "kullanici")
                        .WithMany("Randevu")
                        .HasForeignKey("kullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DayanismaPortali.Service.Model.Vakiflar", "vakif")
                        .WithMany("Randevu")
                        .HasForeignKey("vakifID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kullanici");

                    b.Navigation("vakif");
                });

            modelBuilder.Entity("DayanismaPortali.Service.Model.Vakiflar", b =>
                {
                    b.HasOne("DayanismaPortali.Service.Model.iller", "il")
                        .WithMany("Vakif")
                        .HasForeignKey("ilID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("il");
                });

            modelBuilder.Entity("DayanismaPortali.Service.Model.Kullanicilar", b =>
                {
                    b.Navigation("Randevu");
                });

            modelBuilder.Entity("DayanismaPortali.Service.Model.Vakiflar", b =>
                {
                    b.Navigation("Randevu");
                });

            modelBuilder.Entity("DayanismaPortali.Service.Model.iller", b =>
                {
                    b.Navigation("Kullanici");

                    b.Navigation("Vakif");
                });
#pragma warning restore 612, 618
        }
    }
}
